### ISSUE TITLE
4core CPU with HT shows 8 cores but only 4 active. 

### ISSUE THREAD

**Issue by spxak1** [beaufortfrancois/cog-chrome-app#14]
I have been using Cloudready on my Thinkpad T460p for a while and cog always shows 8 Cores (4physical + 4 HT). 
As of lately (cannot track when this changed) Cog only shows 4 cores active, although 8 are still present.  Is this a Cog issue or did ChromOS stop using HT cores?

Thanks.
![Screenshot 2019-07-02 at 15 23 22](https://user-images.githubusercontent.com/29977030/60520674-b7fc9500-9cdd-11e9-861c-1cc644e84284.png)

**Comment by spxak1** [comment]
A bit of research showed Google killed HT on ChromeOS and as such this is normal behaviour. 8 cores identified but only the 4 physical are operational. 

Sorry for wasting your time.

**Comment by anywhim** [comment]
Actually you can enable it in flags.

**Comment by maks** [comment]
Actually @anywhim the flag will be *ignored* if you use Android or Linux containters:  https://bugs.chromium.org/p/chromium/issues/detail?id=1088305

**Comment by anywhim** [comment]
> Actually @anywhim the flag will be _ignored_ if you use Android or Linux containters: https://bugs.chromium.org/p/chromium/issues/detail?id=1088305

This is true for the devices with some kernels, but I use pixelbook the flag works as expected for me. Of course we should be careful while upgrading our devices but I heard that the next pixelbook will be amd device.

**Comment by maks** [comment]
Ah yes thank you for pointing this out. Yes looks like because the Pixelbook is unaffected as its running a 4.4 kernel it doesn't fall under "newer kernels" by the ChromeOS team so doesn't get the HT being turned off by a VM being run.
