### ISSUE TITLE
Only half the cpu cores usage displayed when hyperthreading enabled

### ISSUE THREAD

**Issue by maks** [beaufortfrancois/cog-chrome-app#16]
on a Dell 5400 running 83.0.4103.97 with hyperthreading enabled via the flag: `chrome://flags/#scheduler-configuration` only half the CPU cores usage is displayed in COG, though all 8 "cores" are displayed in htop running in terminal inside a Crostini container.

I suspect this is actually a ChromeOS bug not returning the data correctly via the [CPU API](https://developer.chrome.com/apps/system_cpu) but I thought I'd start by opening the issue here.

![Screenshot 2020-06-09 at 10 19 31](https://user-images.githubusercontent.com/71999/84092595-30fe8380-aa3b-11ea-9ca5-bbcae7106b4a.png)

**Comment by spxak1** [comment]
> on a Dell 5400 running 83.0.4103.97 with hyperthreading enabled via the flag: `chrome://flags/#scheduler-configuration` only half the CPU cores usage is displayed in COG, though all 8 "cores" are displayed in htop running in terminal inside a Crostini container.
> 
> I suspect this is actually a ChromeOS bug not returning the data correctly via the [CPU API](https://developer.chrome.com/apps/system_cpu) but I thought I'd start by opening the issue here.
> 
> ![Screenshot 2020-06-09 at 10 19 31](https://user-images.githubusercontent.com/71999/84092595-30fe8380-aa3b-11ea-9ca5-bbcae7106b4a.png)

This is ChromeOS/ChromiumOS disabling hyperthreading. Only physical cores are being used. It started with the first large batch of Intel's vulnerabilities issues a couple of years ago. (I may be wrong however).

**Comment by maks** [comment]
@spxak1 I'm afraid that is **not** the case, as I mentioned I explicitly *enabled* hyperthreading using the `scheduler-configuration` flag and as you can see in the screenshot, the Crostini Linux container does show all 8 "cores" as the `i7-8665` I have has 4 cores with 2 threads per core when hyperthreading is enabled.

**Comment by spxak1** [comment]
@maks I am not going to argue, as my response is mostly an attempt in explaining the change in cog going from 8 to 4 cores used (a couple of years ago) when running Chromium OS on my thinkpad. Will watch this thread to see what info comes up. Thanks.

**Comment by maks** [comment]
Hmmm it seems my machine may have been in a bad state, possibly after a suspend, as after rebooting just now COG is showing all hyper threaded cores correctly.

**Comment by maks** [comment]
Well turns out that this is actually due to using Android or Linux containers: https://bugs.chromium.org/p/chromium/issues/detail?id=1088305
