### ISSUE TITLE
Scroll not working in OSX and not showing scrollbars on Windows

### ISSUE THREAD

**Issue by kileras** [beaufortfrancois/cog-chrome-app#2]
I just installed the app in an 27 iMac with Mavericks and Chrome 36 and I cannot do any scroll at all. The trackpad doesn't work and even when I manage to show the scrollbar I cannot drag it either.

**Comment by beaufortfrancois** [comment]
I've just updated the Webstore App at https://chrome.google.com/webstore/detail/cog-system-info-viewer/difcjdggkffcfgcfconafogflmmaadco.
It works fine for me on Google Chrome	41.0.2252.3 (Official Build) dev
